"""
write_log.py  (durable, single-write atomicity boundary for updates that
span multiple physical storages)

THE PROBLEM THIS SOLVES: an "update" whose resolved mutations touch
fields backed by DIFFERENT storages (MDO's column-wise case -- see
core/ontology/mediator.py's _resolve_shared_storage() docstring) has no
way to commit atomically across those genuinely separate physical
databases today -- there is no distributed-transaction coordinator
here, and building one (two-phase commit) would be slow, blocking, and
fragile for exactly the reasons the broader distributed-systems
literature already documents (a coordinator holding locks across
services during a prepare phase, a single point of failure, poor
throughput under load).

THE SOLUTION, matching Palantir Foundry's own actual mechanism
(verified directly against their docs, not assumed -- see
https://www.palantir.com/docs/foundry/object-edits/how-edits-applied):
never attempt to write directly across multiple heterogeneous backends
at all. Write ONE row to THIS single, dedicated, durable store first --
trivially atomic, since it's one write to one place, regardless of how
many storages the update's mutations actually span. Then apply each
storage's own share of the mutations SEQUENTIALLY (matching Palantir's
own confirmed behavior: edits touching multiple objects/storages are
"validated and submitted one at a time," never in parallel). While an
entry is mid-apply (status='pending'), reads (see
core/ontology/mediator.py's get_field()) check here FIRST and return
the pending value if this specific field was part of it -- so a caller
never observes a half-applied state where some storages already
reflect the update and others don't yet.

SCOPE OF THIS FIRST INCREMENT, DELIBERATELY NARROW -- proves the
mechanism against "update" only, against the EXISTING single-object
PendingWrite shape. Explicitly NOT yet covered here (each a real,
separately-scoped follow-up, not silently assumed solved):
  - multi-OBJECT actions (e.g. a transfer touching two different
    objects) -- PendingWrite itself is still single-object; this file
    only ever sees one object_type/object_id per entry.

MULTI-STORAGE CREATE -- once a genuinely separate, harder problem than
update (identity propagation: which storage's row gets the canonical
id, and how does every OTHER storage's row learn it) -- is now solved,
via the SAME log-first-then-apply-sequentially mechanism, with one
real, deliberate constraint: the object's own id MUST be supplied
explicitly in the create's own mutations. Never auto-generated by one
storage and propagated to the others -- this matches Palantir Foundry's
own MDO model directly (verified, not assumed: a multi-datasource
object type's primary key "must exist in every input datasource to
join all datasources" -- see
https://www.palantir.com/docs/foundry/object-permissioning/multi-datasource-objects).

The explicit-id requirement -- and the log-based mechanism itself --
apply to EVERY create now, not just one spanning multiple storages.
Deliberately unified rather than keeping two separately-maintained
mechanisms (a log-based path for multi-storage, a log-free direct path
for single-storage), matching how "update" already works: ONE path,
regardless of storage count, not a branch on it. A genuinely single-
storage create's own INSERT is already atomic on its own and doesn't
NEED the log to avoid a half-applied state the way multi-storage does
-- but requiring every create to go through the SAME mechanism means
there is only ever one code path to reason about, test, and extend,
and it gets the same crash-recovery/audit trail as everything else for
free. See WriteMediator._apply_one_create() and
_resume_one_create_entry() for the write and resume sides.

Still deliberately NOT solved: auto-generated ids for ANY create --
genuinely a separate, harder problem (the id wouldn't be known until
AFTER the storage's own INSERT returns it, breaking the "log
everything up front" ordering this whole mechanism depends on), not
attempted here. Auto-generation used to be supported for a genuinely
single-storage create specifically, before this unification -- a real,
if narrow, capability trade made deliberately, not an oversight.

SEARCH_OBJECT() INTEGRATION -- once a real, stated gap this docstring
used to name explicitly (a search could MISS an object for its own
new, intended value, or WRONGLY include it for the old value it's
about to stop having) -- is now solved too, via DataMediator.
_reconcile_search_with_pending_writes() (see its own docstring for the
full reconciliation logic). write_mediator.py's own
_read_current_state_for_criteria() -- the SAME class of gap, for
submission_criteria evaluation specifically -- is solved the same way,
via the SAME shared DataMediator._read_field_with_log_check() get_field()
itself already used.

CRASH RECOVERY / RESUME-ON-STARTUP -- once the "next planned piece of
work" this docstring itself used to name -- is now solved, via
WriteMediator.resume_pending_writes() (see its own docstring for the
full reconciliation logic: comparing each storage group's LIVE state
against both the intended new values and the original pre-write
values, never blindly re-applying a group that already committed).
Called once, at deployment startup, by both real entry points (api/
app.py's create_app(), scripts/run_deployment.py's run_deployment())
before either serves a single real request. This ALSO closes the
PARTIAL-FAILURE gap the earlier version of this docstring described
separately (an earlier group committing successfully before a later
one failed, non-transiently) -- it's the exact same reconciliation
logic, not a second mechanism.

Still deliberately NOT solved: resume is STARTUP-TIME only, not a
continuously-running background process -- an entry left 'pending'
by a crash that happens WHILE this process keeps running (rather than
one that takes the whole process down) waits for the NEXT restart to
be resolved, same as before. A periodic/background resume loop is a
real, further enhancement, genuinely separately-scoped from proving
the reconciliation logic itself works -- not solved here. Also still
deliberately unsolved: an UPDATE entry resume finds genuinely AMBIGUOUS
(neither the old nor the new value, for some field) is never guessed
at -- logged via core/intermediate_layer/audit.py's
log_write_resume_ambiguous() and left 'pending' for a human to
resolve by hand; there is no automatic reconciliation for this case,
by design, not by omission. A CREATE entry has no equivalent ambiguous
case -- see _resume_one_create_entry()'s own docstring for why a
genuine collision surfaces as a real database error instead.

MULTI-OBJECT BATCHES -- write_log_batches is the atomicity boundary
for an action whose own sub_writes touch MORE than one object (see
core/ontology/write_mediator.py's propose_action() and SubWrite's own
docstrings for the full sub_writes mechanism this builds on). The SAME
"log first, then apply sequentially" principle as everything above,
one level up: ONE row, written before any of a batch's own sub-writes
begin applying, holding the FULL resolved intent (every sub-write's
own object_type/object_id/operation/changes/expected_current_values)
as JSON -- trivially atomic for the identical reason a single
write_log row already is: one INSERT to one table, regardless of how
many objects the batch's own sub_writes ultimately span. Individual
per-object write_log rows (this table's own existing rows, now with a
nullable batch_id linking back) are created ONLY as each sub-write
actually begins applying, not upfront -- exactly mirroring how a
single write_log row itself only gets INSERTed at apply time, not at
propose time (see WriteMediator.propose_action()'s own docstring: it
only ever resolves and returns a PendingWrite, never touches this
class at all).

THE READ-PATH GAP THIS CLOSES: while a batch is mid-apply, some of its
sub-writes may already be fully applied to real storage while others
haven't started yet -- a reader of an EARLIER-applied object would see
its real, changed state while a reader of a NOT-YET-STARTED object in
the SAME logical action would see nothing pending at all (no per-
object write_log row exists for it yet). get_pending_changes() closes
this: if no per-object row exists for an object, it now ALSO checks
every still-pending write_log_batches row's own JSON for that object
-- returning the batch's own intended changes instead of falling
through to real, unrelated storage. The two sources are mutually
exclusive per object at any moment: before a sub-write's own row
exists, only the batch describes it; the instant that row is created,
it takes over and the batch-level entry becomes irrelevant for that
one object specifically -- both are populated from the exact SAME,
already-resolved PendingWrite data (see propose_action()'s own
docstring on why nothing is ever re-resolved between propose and
apply), so there is no possibility of the two disagreeing even in a
race between a reader's two lookups.

A KNOWN, ACCEPTED SCALE TRADE-OFF: the batch-level fallback scans
EVERY still-pending batch's own JSON on a miss, not an indexed lookup
-- get_pending_changes() is already a genuinely hot path (runs on
every DataMediator.get_field() call once this log is enabled at all),
and this adds real, if small, work to it specifically for objects with
no per-object row yet. Acceptable at this project's actual scale
(pending batches are rare and short-lived -- the full apply sequence
for even MAX_SUB_WRITES sub-writes, see core/ontology/action_types.py,
is a bounded handful of sequential round-trips, not something that
stays 'pending' for long) -- but a real, named cost, not something to
rediscover as a surprise if usage patterns ever change.

get_sub_write_entry() and get_all_pending_writes() are this table's
own, correctly-scoped read primitives for the two REAL remaining
consumers of "everything currently pending" -- see each method's own
docstring for exactly what each one needs and why they're genuinely
different needs, not two names for the same query. Both
WriteMediator.confirm_and_execute() and resume_pending_writes() are,
as of this writing, ALREADY rebuilt to use this table's full batch
capability -- see write_mediator.py's own AI-notes for the current,
concrete state of that integration, and this module's own AI-notes at
the bottom for why the older, narrower get_pending_entries() this
replaced no longer served either consumer's real need.

Locking (sorted-order, multi-object) is DataMediator.
_locks_for_objects() (core/ontology/mediator.py) -- built and used by
WriteMediator._apply_batch(), NOT part of this class itself, since
lock ownership belongs with the mediator layer that already owns
_lock_for_object() for the single-object case.

Schema creation is handled by core/sqlite_connection.py's shared
connection_with_schema() -- cached per db_path within this process,
so this table's own CREATE TABLE IF NOT EXISTS only actually runs
once, not on every single call the way it originally did here (a real
cost on a genuinely hot path -- get_pending_changes() runs on every
single DataMediator.get_field() call once this log is enabled).

A CLASS, not a bare module of functions taking db_path on every call
-- refactored deliberately, not incidentally: db_path is genuinely
this mechanism's own persistent state (which file every operation
reads and writes), so it belongs on self, encapsulated the same way
DataMediator and WriteMediator already encapsulate their own state,
rather than re-threaded through every single call's own argument list.
One instance, constructed once at deployment-load time, shared by
DataMediator and WriteMediator alike -- see core/deployment_loader.py.
Sharing the SAME instance (not two separately-constructed ones
pointed at the same path) also structurally eliminates a whole prior
class of misconfiguration: WriteMediator used to take its own,
separate write_log_db_path and explicitly check it matched
DataMediator's own copy at construction time; with one shared
instance there is only ever one value to begin with, nothing left to
accidentally mismatch.
"""

import json
import uuid
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from core.sqlite_connection import connection_with_schema


class WriteLog:
    """
    Durable persistence and read-masking for pending writes -- see this
    module's own docstring for the full mechanism, history, and scope.
    One instance per deployment, shared by DataMediator and
    WriteMediator.
    """

    SCHEMA = """
    CREATE TABLE IF NOT EXISTS write_log (
        id TEXT PRIMARY KEY,
        object_type TEXT NOT NULL,
        object_id TEXT NOT NULL,
        operation TEXT NOT NULL,
        changes TEXT NOT NULL,
        expected_current_values TEXT NOT NULL,
        status TEXT NOT NULL,
        user_id TEXT NOT NULL,
        description TEXT NOT NULL,
        created_at TEXT NOT NULL,
        batch_id TEXT
    );

    CREATE TABLE IF NOT EXISTS write_log_batches (
        id TEXT PRIMARY KEY,
        sub_writes TEXT NOT NULL,
        status TEXT NOT NULL,
        user_id TEXT NOT NULL,
        description TEXT NOT NULL,
        created_at TEXT NOT NULL
    );
    """

    def __init__(self, db_path: Path):
        self._db_path = db_path

    def _connection(self):
        return connection_with_schema(self._db_path, self.SCHEMA)

    def log_pending_update(self, object_type: str, object_id: Any, changes: dict,
                            expected_current_values: dict, user_id: str, description: str,
                            batch_id: str | None = None) -> str:
        # ONE row, ONE write, trivially atomic regardless of how many
        # storages `changes` will eventually resolve across -- this single
        # INSERT is the entire mechanism's real atomicity boundary. Takes
        # the pending write's fields individually rather than a
        # PendingWrite object directly -- this class has no reason to
        # depend on write_mediator.py's own dataclass, keeping the
        # dependency direction strictly one-way (write_mediator depends on
        # this class, never the reverse).
        #
        # batch_id is None for an ordinary, standalone write -- the
        # overwhelming majority of calls, entirely unaffected by this
        # module docstring's own MULTI-OBJECT BATCHES section above. Set
        # only when this row represents one sub-write within a larger
        # write_log_batches entry.
        log_id = str(uuid.uuid4())
        with self._connection() as conn:
            conn.execute(
                "INSERT INTO write_log (id, object_type, object_id, operation, changes, "
                "expected_current_values, status, user_id, description, created_at, batch_id) "
                "VALUES (?, ?, ?, 'update', ?, ?, 'pending', ?, ?, ?, ?)",
                (
                    log_id, object_type, str(object_id), json.dumps(changes),
                    json.dumps(expected_current_values), user_id, description,
                    datetime.now(UTC).isoformat(), batch_id,
                ),
            )
            conn.commit()
        return log_id

    def log_pending_create(self, object_type: str, object_id: Any, changes: dict,
                            user_id: str, description: str, batch_id: str | None = None) -> str:
        # THE create-side counterpart to log_pending_update() above -- no
        # expected_current_values parameter at all, unlike update: there's
        # nothing to compare against or protect from a lost update, since
        # nothing exists yet for this object anywhere. Stored as an empty
        # JSON object in that same column rather than giving create its own
        # separate table -- every other piece of this mechanism
        # (get_pending_changes(), get_all_pending_writes(), the schema
        # itself) stays genuinely shared between both operations; only
        # what gets written into that one column differs.
        log_id = str(uuid.uuid4())
        with self._connection() as conn:
            conn.execute(
                "INSERT INTO write_log (id, object_type, object_id, operation, changes, "
                "expected_current_values, status, user_id, description, created_at, batch_id) "
                "VALUES (?, ?, ?, 'create', ?, '{}', 'pending', ?, ?, ?, ?)",
                (
                    log_id, object_type, str(object_id), json.dumps(changes),
                    user_id, description, datetime.now(UTC).isoformat(), batch_id,
                ),
            )
            conn.commit()
        return log_id

    def mark_applied(self, log_id: str) -> None:
        with self._connection() as conn:
            conn.execute("UPDATE write_log SET status = 'applied' WHERE id = ?", (log_id,))
            conn.commit()

    def log_pending_batch(self, sub_writes: list[dict], user_id: str, description: str) -> str:
        # ONE row, written BEFORE any of the batch's own sub-writes begin
        # applying -- see this module's own MULTI-OBJECT BATCHES docstring
        # section for the full mechanism. sub_writes here is the FULL
        # resolved intent for every sub-write (object_type, object_id,
        # operation, changes, expected_current_values -- each already a
        # plain dict, JSON-serializable directly), not a WriteMediator
        # SubWrite object -- same one-way dependency direction as
        # log_pending_update()/log_pending_create() above.
        batch_id = str(uuid.uuid4())
        with self._connection() as conn:
            conn.execute(
                "INSERT INTO write_log_batches (id, sub_writes, status, user_id, description, created_at) "
                "VALUES (?, ?, 'pending', ?, ?, ?)",
                (batch_id, json.dumps(sub_writes), user_id, description, datetime.now(UTC).isoformat()),
            )
            conn.commit()
        return batch_id

    def mark_batch_applied(self, batch_id: str) -> None:
        with self._connection() as conn:
            conn.execute("UPDATE write_log_batches SET status = 'applied' WHERE id = ?", (batch_id,))
            conn.commit()

    def get_pending_batches(self) -> list[dict]:
        # The batch-level entry point WriteMediator.resume_pending_
        # writes() walks to find every INCOMPLETE multi-object action,
        # including one that crashed before even its FIRST sub-write
        # got its own write_log row (in which case a query scoped to
        # write_log alone would show nothing for it at all -- see
        # get_sub_write_entry()'s own docstring for how resume checks
        # each sub-write's OWN status once it has this batch's list to
        # walk). Returns id/sub_writes (already json.loads()'d)/
        # user_id/description.
        with self._connection() as conn:
            rows = conn.execute(
                "SELECT id, sub_writes, user_id, description FROM write_log_batches WHERE status = 'pending'"
            ).fetchall()
        return [
            {
                "id": row["id"],
                "sub_writes": json.loads(row["sub_writes"]),
                "user_id": row["user_id"],
                "description": row["description"],
            }
            for row in rows
        ]

    def get_pending_changes(self, object_type: str, object_id: Any) -> dict | None:
        # Used by DataMediator.get_field() -- returns this object's pending
        # field->value changes if a write_log entry for it is still
        # mid-apply, else None. A caller merges this OVER whatever the real
        # backend currently holds, so a read never observes a half-applied
        # state (some storages already written, others not yet).
        #
        # object_id is explicitly str()-converted on both the write side
        # (log_pending_update/log_pending_create above) and here -- SQLite's
        # dynamic typing would happily store e.g. an int object_id in this
        # TEXT column, but comparing that stored int against a TEXT literal
        # at query time depends on SQLite's type-affinity rules in a way
        # that's easy to get subtly wrong. Converting explicitly,
        # consistently, on both sides removes that ambiguity entirely
        # rather than relying on it working out.
        #
        # fetchone(), not fetchall() -- assumes at most one pending entry
        # per object at a time, which holds as long as callers keep this
        # object's own per-object lock (see DataMediator._lock_for_object())
        # held across the full log-write-then-apply sequence, not just the
        # apply portion -- see write_mediator.py's own confirm_and_execute().
        with self._connection() as conn:
            row = conn.execute(
                "SELECT changes FROM write_log WHERE object_type = ? AND object_id = ? "
                "AND status = 'pending'",
                (object_type, str(object_id)),
            ).fetchone()
        if row is not None:
            return json.loads(row["changes"])

        # No per-object row yet -- see this module's own MULTI-OBJECT
        # BATCHES docstring section for why a still-pending batch might
        # ALREADY declare real intent for this object, even though its
        # own sub-write hasn't started applying (and so has no write_log
        # row of its own) yet.
        for batch in self.get_pending_batches():
            for sub_write in batch["sub_writes"]:
                if sub_write["object_type"] == object_type and str(sub_write["object_id"]) == str(object_id):
                    return sub_write["changes"]
        return None

    def get_sub_write_entry(self, batch_id: str, object_type: str, object_id: Any) -> dict | None:
        # ONE specific sub-write's own write_log row within a batch, if
        # it exists yet AT ALL -- regardless of status (pending OR
        # applied), unlike get_pending_changes() above, which only ever
        # returns something for a still-PENDING row. Used by
        # WriteMediator.resume_pending_writes() to determine, per sub_
        # write, which of three states it's in: not started (None
        # here -- no row exists), mid-apply (status='pending'), or
        # already done (status='applied') -- see that method's own
        # docstring for the full three-way dispatch this supports.
        #
        # At most one row can ever match -- propose_action()'s own
        # full, resolved-id duplicate check (core/ontology/write_
        # mediator.py) guarantees each (object_type, object_id) pair
        # appears at most once within any single batch, so fetchone()
        # here is exactly as safe as get_pending_changes()'s own.
        with self._connection() as conn:
            row = conn.execute(
                "SELECT id, object_type, object_id, operation, changes, expected_current_values, "
                "status, user_id, description FROM write_log "
                "WHERE batch_id = ? AND object_type = ? AND object_id = ?",
                (batch_id, object_type, str(object_id)),
            ).fetchone()
        if row is None:
            return None
        return {
            "id": row["id"],
            "object_type": row["object_type"],
            "object_id": row["object_id"],
            "operation": row["operation"],
            "changes": json.loads(row["changes"]),
            "expected_current_values": json.loads(row["expected_current_values"]),
            "status": row["status"],
            "user_id": row["user_id"],
            "description": row["description"],
        }

    def get_all_pending_writes(self) -> list[dict]:
        # Every object with SOME pending intent right now, regardless
        # of whether its own write_log row exists yet (mid-apply) or
        # it's still only described by a pending batch (not yet
        # started at all) -- the flat-list, reconciliation-scale
        # counterpart to get_pending_changes()'s own per-object check.
        # Used by DataMediator._reconcile_search_with_pending_writes()
        # -- a search must never miss or wrongly include an object
        # because of EITHER kind of pending intent, not just the
        # mid-apply kind a query scoped to this table alone would see.
        #
        # No "id" field -- unlike this class's own former
        # get_pending_entries() (retired; this replaces it, correctly
        # scoped for the callers that actually remain, see this
        # module's own AI-notes for why), meaningless here: a not-yet-
        # started sub-write has no write_log row of its own at all yet.
        #
        # Per-object write_log rows take priority over a batch's own
        # declaration for the SAME object -- mirrors get_pending_
        # changes()'s own priority order; in practice these can only
        # ever differ during the brief window a sub_write is being
        # promoted from "described only by the batch" to "has its own
        # row."
        seen: set[tuple[str, str]] = set()
        results = []
        with self._connection() as conn:
            rows = conn.execute(
                "SELECT object_type, object_id, operation, changes, expected_current_values, "
                "user_id, description FROM write_log WHERE status = 'pending'"
            ).fetchall()
        for row in rows:
            seen.add((row["object_type"], row["object_id"]))
            results.append({
                "object_type": row["object_type"],
                "object_id": row["object_id"],
                "operation": row["operation"],
                "changes": json.loads(row["changes"]),
                "expected_current_values": json.loads(row["expected_current_values"]),
                "user_id": row["user_id"],
                "description": row["description"],
            })

        for batch in self.get_pending_batches():
            for sub_write in batch["sub_writes"]:
                key = (sub_write["object_type"], str(sub_write["object_id"]))
                if key in seen:
                    continue
                seen.add(key)
                results.append({
                    "object_type": sub_write["object_type"],
                    "object_id": sub_write["object_id"],
                    "operation": sub_write["operation"],
                    "changes": sub_write["changes"],
                    "expected_current_values": sub_write["expected_current_values"],
                    "user_id": batch["user_id"],
                    "description": batch["description"],
                })
        return results


# =============================================================================
# AI-ONLY NOTES -- not user-facing. Context for a future AI session (or me,
# later) that lacks this conversation's history. Update this section whenever
# something genuinely open, deferred, or rejected comes up for this file.
# =============================================================================
#
# OPEN QUESTIONS:
# - (RESOLVED, keeping for history) Sorted-order lock acquisition for a
#   multi-sub-write batch was an open question as of this file's first
#   AI-notes pass -- now BUILT: DataMediator._locks_for_objects()
#   (core/ontology/mediator.py), used by write_mediator.py's own
#   _apply_batch(). Sorted (object_type, str(object_id)) order for
#   acquisition (deadlock avoidance); sub_writes' own declared LIST
#   order for actual apply (referential correctness). Still two
#   genuinely different orderings -- don't let them collapse into one.
#
# DEFERRED (known, intentional, not yet built):
# - (UPDATED -- was "confirm_and_execute() still only ever applies
#   sub_writes[0]," no longer true) confirm_and_execute() now ALWAYS
#   goes through _apply_batch(), one sub_write or many, and this
#   file's own batch capability (log_pending_batch, get_pending_
#   batches, the batch_id column, the get_pending_changes() fallback)
#   is genuinely exercised by every real write now -- see
#   tests/unit/test_confirm_and_execute_batches.py for direct,
#   empirical proof (not just inference) that a real write_log_
#   batches row exists mid-apply and the per-object row is correctly
#   batch-owned. What's NOT yet done, and is urgent, not just
#   deferred: resume_pending_writes() (write_mediator.py) has not been
#   rebuilt to match -- see that file's own AI-notes section (added at
#   the same time as this update) for the full, concrete consequence,
#   which is more serious than "incomplete": crash recovery for real,
#   confirm_and_execute()-originated writes is currently a silent
#   no-op, not merely partial.
# - No real, multi-object action_type has ever been declared or
#   exercised anywhere -- only synthetic test fixtures. Still true as
#   of this update. The first REAL one (a funds transfer, most likely)
#   should be authored once resume is ALSO ready to handle it
#   correctly, as the genuine end-to-end proof this whole mechanism
#   works -- not before, since a crash mid-apply on a real multi-
#   object action would currently be unrecoverable, per the point
#   above.
#
# REJECTED ALTERNATIVES (considered and ruled out -- don't re-propose
# without reading why):
# - A separate, always-current "live index" tier (Palantir's own real
#   architecture: an offset-tracked queue + a fast index, with the real
#   backing dataset lagging behind via periodic/triggered flush) was
#   considered, via direct research into Palantir's actual mechanism,
#   and deliberately NOT built here. The read-consistency GUARANTEE
#   matches Palantir's own (a reader never sees a torn, half-applied
#   multi-object state); the MECHANISM achieving it is a simpler analog
#   suited to Elysium's much smaller, single-process scale -- checking
#   the durable log directly at read time, no separate indexing
#   subsystem. This was an explicit, discussed trade-off, not an
#   oversight -- flagged as something to possibly revisit "at a future
#   point in time" if Elysium's scale or requirements ever change
#   enough to warrant it, per the user's own words when this was
#   discussed.
#
# KNOWN LIMITATIONS:
# - get_pending_changes()'s batch-fallback scans EVERY still-pending
#   batch's own JSON on a per-object-row miss -- not an indexed lookup.
#   Accepted as fine at Elysium's actual scale (pending batches are
#   rare and short-lived) but a real, named cost -- see this file's own
#   module docstring for the full reasoning, not just this note.
