"""
write_log.py  (durable, single-write atomicity boundary for updates that
span multiple physical storages)

THE PROBLEM THIS SOLVES: an "update" whose resolved mutations touch
fields backed by DIFFERENT storages (MDO's column-wise case -- see
core/ontology/mediator.py's _resolve_shared_storage() docstring) has no
way to commit atomically across those genuinely separate physical
databases today -- there is no distributed-transaction coordinator
here, and building one (two-phase commit) would be slow, blocking, and
fragile for exactly the reasons the broader distributed-systems
literature already documents (a coordinator holding locks across
services during a prepare phase, a single point of failure, poor
throughput under load).

THE SOLUTION, matching Palantir Foundry's own actual mechanism
(verified directly against their docs, not assumed -- see
https://www.palantir.com/docs/foundry/object-edits/how-edits-applied):
never attempt to write directly across multiple heterogeneous backends
at all. Write ONE row to THIS single, dedicated, durable store first --
trivially atomic, since it's one write to one place, regardless of how
many storages the update's mutations actually span. Then apply each
storage's own share of the mutations SEQUENTIALLY (matching Palantir's
own confirmed behavior: edits touching multiple objects/storages are
"validated and submitted one at a time," never in parallel). While an
entry is mid-apply (status='pending'), reads (see
core/ontology/mediator.py's get_field()) check here FIRST and return
the pending value if this specific field was part of it -- so a caller
never observes a half-applied state where some storages already
reflect the update and others don't yet.

SCOPE OF THIS FIRST INCREMENT, DELIBERATELY NARROW -- proves the
mechanism against "update" only, against the EXISTING single-object
PendingWrite shape. Explicitly NOT yet covered here (each a real,
separately-scoped follow-up, not silently assumed solved):
  - multi-OBJECT actions (e.g. a transfer touching two different
    objects) -- PendingWrite itself is still single-object; this file
    only ever sees one object_type/object_id per entry.

MULTI-STORAGE CREATE -- once a genuinely separate, harder problem than
update (identity propagation: which storage's row gets the canonical
id, and how does every OTHER storage's row learn it) -- is now solved,
via the SAME log-first-then-apply-sequentially mechanism, with one
real, deliberate constraint: the object's own id MUST be supplied
explicitly in the create's own mutations. Never auto-generated by one
storage and propagated to the others -- this matches Palantir Foundry's
own MDO model directly (verified, not assumed: a multi-datasource
object type's primary key "must exist in every input datasource to
join all datasources" -- see
https://www.palantir.com/docs/foundry/object-permissioning/multi-datasource-objects).

The explicit-id requirement -- and the log-based mechanism itself --
apply to EVERY create now, not just one spanning multiple storages.
Deliberately unified rather than keeping two separately-maintained
mechanisms (a log-based path for multi-storage, a log-free direct path
for single-storage), matching how "update" already works: ONE path,
regardless of storage count, not a branch on it. A genuinely single-
storage create's own INSERT is already atomic on its own and doesn't
NEED the log to avoid a half-applied state the way multi-storage does
-- but requiring every create to go through the SAME mechanism means
there is only ever one code path to reason about, test, and extend,
and it gets the same crash-recovery/audit trail as everything else for
free. See WriteMediator._apply_create_via_log() and
_resume_one_create_entry() for the write and resume sides.

Still deliberately NOT solved: auto-generated ids for ANY create --
genuinely a separate, harder problem (the id wouldn't be known until
AFTER the storage's own INSERT returns it, breaking the "log
everything up front" ordering this whole mechanism depends on), not
attempted here. Auto-generation used to be supported for a genuinely
single-storage create specifically, before this unification -- a real,
if narrow, capability trade made deliberately, not an oversight.

SEARCH_OBJECT() INTEGRATION -- once a real, stated gap this docstring
used to name explicitly (a search could MISS an object for its own
new, intended value, or WRONGLY include it for the old value it's
about to stop having) -- is now solved too, via DataMediator.
_reconcile_search_with_pending_writes() (see its own docstring for the
full reconciliation logic). write_mediator.py's own
_read_current_state_for_criteria() -- the SAME class of gap, for
submission_criteria evaluation specifically -- is solved the same way,
via the SAME shared DataMediator._read_field_with_log_check() get_field()
itself already used.

CRASH RECOVERY / RESUME-ON-STARTUP -- once the "next planned piece of
work" this docstring itself used to name -- is now solved, via
WriteMediator.resume_pending_writes() (see its own docstring for the
full reconciliation logic: comparing each storage group's LIVE state
against both the intended new values and the original pre-write
values, never blindly re-applying a group that already committed).
Called once, at deployment startup, by both real entry points (api/
app.py's create_app(), scripts/run_deployment.py's run_deployment())
before either serves a single real request. This ALSO closes the
PARTIAL-FAILURE gap the earlier version of this docstring described
separately (an earlier group committing successfully before a later
one failed, non-transiently) -- it's the exact same reconciliation
logic, not a second mechanism.

Still deliberately NOT solved: resume is STARTUP-TIME only, not a
continuously-running background process -- an entry left 'pending'
by a crash that happens WHILE this process keeps running (rather than
one that takes the whole process down) waits for the NEXT restart to
be resolved, same as before. A periodic/background resume loop is a
real, further enhancement, genuinely separately-scoped from proving
the reconciliation logic itself works -- not solved here. Also still
deliberately unsolved: an UPDATE entry resume finds genuinely AMBIGUOUS
(neither the old nor the new value, for some field) is never guessed
at -- logged via core/intermediate_layer/audit.py's
log_write_resume_ambiguous() and left 'pending' for a human to
resolve by hand; there is no automatic reconciliation for this case,
by design, not by omission. A CREATE entry has no equivalent ambiguous
case -- see _resume_one_create_entry()'s own docstring for why a
genuine collision surfaces as a real database error instead.


Schema creation is handled by core/sqlite_connection.py's shared
connection_with_schema() -- cached per db_path within this process,
so this table's own CREATE TABLE IF NOT EXISTS only actually runs
once, not on every single call the way it originally did here (a real
cost on a genuinely hot path -- get_pending_changes() runs on every
single DataMediator.get_field() call once this log is enabled).

db_path is always an explicit parameter, never a hardcoded global path
-- same dependency-injection discipline as every other adapter in this
project (see core/auth/database.py's own docstring for the identical
reasoning, applied here to a different problem). Uses
core/sqlite_connection.py's shared connection_with_schema() -- the
SAME mechanical connection-opening-and-schema-verification code
core/auth/database.py now also uses, not a second, independently-
written copy of the same pattern.
"""

import json
import uuid
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from core.sqlite_connection import connection_with_schema

SCHEMA = """
CREATE TABLE IF NOT EXISTS write_log (
    id TEXT PRIMARY KEY,
    object_type TEXT NOT NULL,
    object_id TEXT NOT NULL,
    operation TEXT NOT NULL,
    changes TEXT NOT NULL,
    expected_current_values TEXT NOT NULL,
    status TEXT NOT NULL,
    user_id TEXT NOT NULL,
    description TEXT NOT NULL,
    created_at TEXT NOT NULL
);
"""


def connection(db_path: Path):
    return connection_with_schema(db_path, SCHEMA)


def log_pending_update(db_path: Path, object_type: str, object_id: Any, changes: dict,
                        expected_current_values: dict, user_id: str, description: str) -> str:
    # ONE row, ONE write, trivially atomic regardless of how many
    # storages `changes` will eventually resolve across -- this single
    # INSERT is the entire mechanism's real atomicity boundary. Takes
    # the pending write's fields individually rather than a
    # PendingWrite object directly -- this module has no reason to
    # depend on write_mediator.py's own dataclass, keeping the
    # dependency direction strictly one-way (write_mediator depends on
    # this module, never the reverse).
    log_id = str(uuid.uuid4())
    with connection(db_path) as conn:
        conn.execute(
            "INSERT INTO write_log (id, object_type, object_id, operation, changes, "
            "expected_current_values, status, user_id, description, created_at) "
            "VALUES (?, ?, ?, 'update', ?, ?, 'pending', ?, ?, ?)",
            (
                log_id, object_type, str(object_id), json.dumps(changes),
                json.dumps(expected_current_values), user_id, description,
                datetime.now(UTC).isoformat(),
            ),
        )
        conn.commit()
    return log_id


def log_pending_create(db_path: Path, object_type: str, object_id: Any, changes: dict,
                        user_id: str, description: str) -> str:
    # THE create-side counterpart to log_pending_update() above -- no
    # expected_current_values parameter at all, unlike update: there's
    # nothing to compare against or protect from a lost update, since
    # nothing exists yet for this object anywhere. Stored as an empty
    # JSON object in that same column rather than giving create its own
    # separate table -- every other piece of this mechanism
    # (get_pending_changes(), get_pending_entries(), the schema itself)
    # stays genuinely shared between both operations; only what gets
    # written into that one column differs.
    log_id = str(uuid.uuid4())
    with connection(db_path) as conn:
        conn.execute(
            "INSERT INTO write_log (id, object_type, object_id, operation, changes, "
            "expected_current_values, status, user_id, description, created_at) "
            "VALUES (?, ?, ?, 'create', ?, '{}', 'pending', ?, ?, ?)",
            (
                log_id, object_type, str(object_id), json.dumps(changes),
                user_id, description, datetime.now(UTC).isoformat(),
            ),
        )
        conn.commit()
    return log_id


def mark_applied(db_path: Path, log_id: str) -> None:
    with connection(db_path) as conn:
        conn.execute("UPDATE write_log SET status = 'applied' WHERE id = ?", (log_id,))
        conn.commit()


def get_pending_changes(db_path: Path, object_type: str, object_id: Any) -> dict | None:
    # Used by DataMediator.get_field() -- returns this object's pending
    # field->value changes if a write_log entry for it is still
    # mid-apply, else None. A caller merges this OVER whatever the real
    # backend currently holds, so a read never observes a half-applied
    # state (some storages already written, others not yet).
    #
    # object_id is explicitly str()-converted on both the write side
    # (log_pending_write above) and here -- SQLite's dynamic typing
    # would happily store e.g. an int object_id in this TEXT column,
    # but comparing that stored int against a TEXT literal at query
    # time depends on SQLite's type-affinity rules in a way that's
    # easy to get subtly wrong. Converting explicitly, consistently, on
    # both sides removes that ambiguity entirely rather than relying on
    # it working out.
    #
    # fetchone(), not fetchall() -- assumes at most one pending entry
    # per object at a time, which holds as long as callers keep this
    # object's own per-object lock (see DataMediator._lock_for_object())
    # held across the full log-write-then-apply sequence, not just the
    # apply portion -- see write_mediator.py's own confirm_and_execute().
    with connection(db_path) as conn:
        row = conn.execute(
            "SELECT changes FROM write_log WHERE object_type = ? AND object_id = ? "
            "AND status = 'pending'",
            (object_type, str(object_id)),
        ).fetchone()
    if row is None:
        return None
    return json.loads(row["changes"])


def get_pending_entries(db_path: Path) -> list[dict]:
    # Used by WriteMediator.resume_pending_writes() -- EVERY entry
    # still at status='pending', across every object, not scoped to
    # one object the way get_pending_changes() above is. This is the
    # actual resume/crash-recovery entry point: a genuine crash mid-
    # apply leaves an entry here with no further trace anywhere else
    # (the process that would have called mark_applied() is simply
    # gone), so resuming after a restart means finding every such
    # entry and reconciling it against live backend state -- see
    # WriteMediator.resume_pending_writes()'s own docstring for that
    # reconciliation logic.
    #
    # Returns entry_id/object_type/object_id/operation/changes/
    # expected_current_values/user_id/description, changes and
    # expected_current_values already json.loads()'d -- the caller
    # needs them as real dicts, not JSON strings, to compare against
    # live field values.
    with connection(db_path) as conn:
        rows = conn.execute(
            "SELECT id, object_type, object_id, operation, changes, expected_current_values, "
            "user_id, description FROM write_log WHERE status = 'pending'"
        ).fetchall()
    return [
        {
            "id": row["id"],
            "object_type": row["object_type"],
            "object_id": row["object_id"],
            "operation": row["operation"],
            "changes": json.loads(row["changes"]),
            "expected_current_values": json.loads(row["expected_current_values"]),
            "user_id": row["user_id"],
            "description": row["description"],
        }
        for row in rows
    ]
