"""What a password must be, when a PERSON chooses it.

NIST SP 800-63B REVISION 4, finalised mid-2025, and followed rather than
the habits it replaced:

  LENGTH, NOT COMPOSITION. "When a password is the only authenticator,
  systems must enforce a minimum length of 15 characters" -- and Elysium
  has no second factor, so 15. No "one uppercase, one symbol": those
  produce Spring2025! and nothing stronger.

  LONG PASSPHRASES WELCOME. Accept at least 64 characters, spaces and
  Unicode included, so a password manager or a sentence works.

  NO FORCED ROTATION. Change on evidence of compromise, not a calendar.

  A BLOCKLIST of "commonly used, expected, or compromised values". Most
  implementations call Have I Been Pwned; a self-hosted Elysium may
  have no internet, so this list works OFFLINE: common long passwords,
  the username, the service's own name, and repeated or sequential
  runs -- the "expected" values NIST names.

WHERE IT APPLIES: at the boundary where a person chooses -- creating an
account, changing one's own password, an administrator's reset. NOT in
UserDirectory, which scripts and tests build on: enforcing there would
break them without making anything safer. The first administrator's
password is generated by bootstrap_root.py -- 32 random characters --
so it never meets a person's choice at all.

NOT NORMALISED, deliberately. NIST recommends NFKC normalisation before
hashing, but passwords already stored were hashed without it; turning
it on would lock out anybody whose password contains a character NFKC
changes.
"""

MIN_LENGTH = 15
# A CEILING, not the 64 NIST's floor asks us to accept: argon2 hashes
# whatever it is given, and an unbounded password is a cheap way to make
# the server do expensive work.
MAX_LENGTH = 256

# COMMON PASSWORDS AT LEAST 15 LONG. A short common password is already
# refused by length, so only the long ones need listing.
_COMMON = frozenset({
    "passwordpassword", "password12345678", "password1234567",
    "123456789012345", "1234567890123456", "12345678901234567890",
    "qwertyuiopasdfgh", "qwertyuiopasdfghjkl", "qwertyuiop123456",
    "iloveyouiloveyou", "letmeinletmein", "welcomewelcome1",
    "administrator123", "adminadminadmin", "changemechangeme",
    "correcthorsebatterystaple", "trustno1trustno1",
})

_SERVICE_NAMES = ("elysium",)


def _is_repetition(password: str) -> bool:
    """One short unit repeated to fill the length: "aaaaaaaaaaaaaaa",
    "abcabcabcabcabc"."""
    for size in range(1, 5):
        unit = password[:size]
        if unit * (len(password) // size) + unit[: len(password) % size] == password:
            return True
    return False


def _is_sequence(password: str) -> bool:
    """A run where every character is one step from the last:
    "abcdefghijklmno", "zyxwvutsrqponml". Digits that roll over from 9
    to 0 are NOT a single step and not caught here -- the common ones
    are on the list above instead."""
    # UNEVEN ON PURPOSE: each character paired with the one after it.
    steps = {ord(b) - ord(a) for a, b in zip(password, password[1:], strict=False)}
    return steps in ({1}, {-1})


def _is_the_username_or_a_derivative(lowered: str, username: str) -> bool:
    """The password IS the username, or BEGINS with it.

    NOT "contains it anywhere", WHICH IS WHAT THIS USED TO DO. SEC-22,
    raised by the security agent: any password holding the username as
    a substring was refused, so `my-alice-in-wonderland-quote` --
    twenty-eight characters -- was rejected for the user `alice`, as
    was `malice-in-the-palace`, which contains those letters by
    accident of English.

    NIST SP 800-63B objects to the substring scan in normative
    language: "the entire password SHALL be subject to comparison, NOT
    SUBSTRINGS OR WORDS THAT MIGHT BE CONTAINED THEREIN", and its own
    reasoning is that an over-broad blocklist "is likely to frustrate
    users that attempt to choose a memorable password" -- a frustrated
    user picks something shorter.

    BUT THE SAME DOCUMENT LISTS "the username, AND DERIVATIVES
    THEREOF", and a password BEGINNING with the username is a
    derivative in the way one merely containing it is not: it is what
    somebody types when asked to make a password out of their name.
    Two tests in this project encoded exactly that case deliberately --
    `alice-has-a-long-secret` and `cyrus-and-a-long-tail` -- and I
    nearly loosened both before reading why they were there.

    So: refuse the username itself, the username with characters
    appended or padded around it, and a password that STARTS with it.
    Accept one that happens to contain it somewhere else.
    """
    import re

    if lowered == username or lowered.startswith(username):
        return True
    # A derivative with punctuation woven through it: strip everything
    # that is not a letter and see whether the username is what is
    # left. "a.l.i.c.e!!" reduces to "alice"; a real passphrase does
    # not.
    return re.sub(r"[^a-z]", "", lowered) == username


def password_problem(password: str, username: str) -> str | None:
    """Why this password may not be chosen, or None.

    THE MESSAGE SAYS WHAT TO DO, because the person reading it is about
    to choose again -- and it never repeats the password back.
    """
    if not isinstance(password, str):
        return "A password must be text."
    if len(password) < MIN_LENGTH:
        return (
            f"A password needs at least {MIN_LENGTH} characters. A few words "
            f"together work well -- length matters far more than symbols."
        )
    if len(password) > MAX_LENGTH:
        return f"A password can be at most {MAX_LENGTH} characters."

    lowered = password.lower()
    # SEPARATORS DO NOT MAKE A PASSWORD LESS COMMON. "correct horse
    # battery staple" -- spaces and all -- is the most famous password
    # there is, and a first version accepted it because the list held it
    # without spaces.
    squeezed = "".join(ch for ch in lowered if ch.isalnum())
    if lowered in _COMMON or squeezed in _COMMON:
        return "That password is too common to use. Choose something less predictable."
    if username and _is_the_username_or_a_derivative(lowered, username.lower()):
        return "A password must not be your username, or your username with "\
               "characters added."
    for name in _SERVICE_NAMES:
        if name in lowered:
            return f"A password must not contain {name!r}."
    if _is_repetition(password):
        return "A password must not be one short pattern repeated."
    if _is_sequence(password):
        return "A password must not be a simple sequence."
    return None
